### PR TITLE
general overflowing support and minor fixes

### PR DESCRIPTION
**Pull request by chengxuz**
Changed the overflowing detection to more general settings.

Fix some gpu tensor issues.

### CODE REVIEW

**Comment by mschrimpf** [comment]
just pinging this; looks like unit tests are failing

**Comment by chengxuz** [comment]
How should I reproduce the error?

**Comment by mschrimpf** [comment]
Every travis run starts from a blank environment and then follows the steps in [.travis.yml](https://github.com/brain-score/language/blob/main/.travis.yml) to set up and run tests. Looks like it's raising several `KeyError: 'overflowing_tokens'` (see e.g. https://app.travis-ci.com/github/brain-score/language/jobs/599269707)

**Comment by mschrimpf** [comment]
looks like the last failed test was unrelated, just merged main, let's see if that resolves it

**Review by mschrimpf — APPROVED** [review]

**Comment by mschrimpf** [comment]
Hi @chengxuz, sorry for the delay on this. @kvfairchild and I investigated and the remaining error is due to accessing secrets from a PR originating from a fork. We'll fix this in #170, then merge into this PR, so that we can hopefully merge by end-of-day.

**Comment by mschrimpf** [comment]
@chengxuz it looks like there is one remaining error in the model wrapper implementation.

**Pull request merged**
