### PR TITLE
Syntaxgym fixes: benchmark prefix, ceilings, imports, remove root benchmark from registry

### PR DESCRIPTION
**Pull request by mschrimpf**
without the benchmark prefixes, the `benchmark_registry` will include keys like `center_embed` or `npi_orc_any` that I believe will not be immediately clear. `syntaxgym-center_embed` and `syntaxgym-npi_orc_any` on the other hand are more obvious.

rationale for removing root benchmark from registry: otherwise it sets a bad precedent where future benchmark additions would include the root benchmark and that would then automatically be run. In the long run, we might be able to mark such root entries as being excluded from submission system runs.

### CODE REVIEW

**Review by kvfairchild — APPROVED** [review]

**Comment by jimn2** [comment]
I agree with the logic of adding the prefixes.

The name "syntaxgym-2020" might be a bit misleading.  It's not so much a root benchmark as it gives an additional capability to run several individual benchmarks automatically and return an average score (along with individual scores).  I'd like to double check the documentation to make sure this is explained somewhere (so the capability isn't lost in the ether) but the Documentation link in README.md appears to be broken.

**Review by jimn2 — COMMENTED** [review]
I agree with the logic of adding the prefixes.

The name "syntaxgym-2020" might be a bit misleading. It's not so much a root benchmark as it gives an additional capability to run several individual benchmarks automatically and return an average score (along with individual scores). I'd like to double check the documentation to make sure this is explained somewhere (so the capability isn't lost in the ether) but the Documentation link in README.md appears to be broken.

**Comment by mschrimpf** [comment]
Just to make sure we're on the same page: this PR actually removes the root benchmark `syntaxgym-2020` to avoid models automatically being scored on it.
For "local library users" to run several individual benchmarks automatically, they would thus have to instantiate `SyntaxGym2020()`. Not sure if "2020" makes sense, it could just be "SynaxGym".

**Comment by jimn2** [comment]
Right...I understood the removal.  It doesn't really fit with the individual benchmarks, and it actually can take a long time to run, so it's good to keep it from being run automatically.

The "2020" is a reference to a seminal SyntaxGym paper in which these 31 benchmarks were evaluated/compared.  But I believe I included that reference in the documentation for the benchmark.  I think switching the name to syntaxgym-auto-avg or something like that might be more intuitive for indicating the actual use of that benchmark.

**Comment by jimn2** [comment]
I'd go ahead and merge this one.  I'll submit another PR to change that name and double-check that the documentation explains what that syntaxgym-2020 benchmark is actually doing.  I'll request a review from Jon G as he was one of the authors on that 2020 SG paper and is the person that named this benchmark syntaxgym-2020.

(I won't get to it till tomorrow though)

**Pull request merged**
