### PR TITLE
Change metric name "linear" to "linreg_pearsonr"

### PR DESCRIPTION
**Pull request by gretatuckute**
Change metric name "linear" to "linreg_pearsonr" given that the linear metric consists of linear regression with pearson correlation. We want to be able to create benchmarks that use different evaluation metrics and hence need naming conventions to support this.

Changed this for the metric names, but did **not** change the Pereira Class name (_Pereira2018ExperimentLinear) and the ceiling identifier (identifier = f'Pereira2018.{experiment}-linear'). @mschrimpf do you want to change these too such that it matches this convention (I did not want to change it to not mess up loading of ceilings/data).

### CODE REVIEW

**Comment by mschrimpf** [comment]
> Changed this for the metric names, but did **not** change the Pereira Class name (_Pereira2018ExperimentLinear) and the ceiling identifier (identifier = f'Pereira2018.{experiment}-linear'). @mschrimpf do you want to change these too such that it matches this convention (I did not want to change it to not mess up loading of ceilings/data).

happy to change the ceiling name if you prefer! let me know.

**Comment by gretatuckute** [comment]
> > Changed this for the metric names, but did **not** change the Pereira Class name (_Pereira2018ExperimentLinear) and the ceiling identifier (identifier = f'Pereira2018.{experiment}-linear'). @mschrimpf do you want to change these too such that it matches this convention (I did not want to change it to not mess up loading of ceilings/data).
> 
> happy to change the ceiling name if you prefer! let me know.

Ok, thanks -- yes, that'd be great.

**Comment by mschrimpf** [comment]
> > > Changed this for the metric names, but did **not** change the Pereira Class name (_Pereira2018ExperimentLinear) and the ceiling identifier (identifier = f'Pereira2018.{experiment}-linear'). @mschrimpf do you want to change these too such that it matches this convention (I did not want to change it to not mess up loading of ceilings/data).
> > 
> > 
> > happy to change the ceiling name if you prefer! let me know.
> 
> Ok, thanks -- yes, that'd be great. Also, do you want to change the class name too?

up to you, I'm happy to leave as-is, but if you're going to introduce linear non-pearson benchmarks on the same data, it should probably be changed

**Comment by mschrimpf** [comment]
@gretatuckute any updates on this PR?

**Comment by gretatuckute** [comment]
> 

I thought this was all set and resolved, no? We have changed the linreg nomenclature in the branch where we update the Pereira benchmarks.

**Comment by mschrimpf** [comment]
Unit tests are failing though, e.g. in `brainscore_language/benchmarks/pereira2018/test.py:54` (`TestBenchmark.test_dummy_bad`): `KeyError: 'Pereira2018.243sentences-linear'` (from `load_benchmark(f'Pereira2018.{experiment}sentences-linear')`)

**Comment by mschrimpf** [comment]
Sorry, this PR was closed after combining commit history. @gretatuckute can you please open a new PR?

**Comment by gretatuckute** [comment]
> Sorry, this PR was closed after combining commit history. @gretatuckute can you please open a new PR? I'm afraid the simplest solution is to 1. checkout the branch locally, 2. copy all files into a separate location, 3. checkout main, 4. update main, 5. create a new branch, 6. copy all files back again overwriting the files in main, 7. push and open a PR.

Hm, I think we might want to merge these edits with the "towards adding Pereira2018ROI as a benchmark #37" PR because that was the reason the units tests were failing.

**Comment by aalok-sathe** [comment]
I think most of these edits are already incorporated into the former PR #37 (although not specifically by way of the commits on this PR). So when that gets merged, they will automatically make their way. The alternative is we merge this into main independently and merge main into the former #37. 
What do you think is preferable?

**Pull request closed without merging**
