### PR TITLE
show progress bar only if more than 100 items

### PR DESCRIPTION
**Pull request by mschrimpf**

### CODE REVIEW

**Review by benlipkin — COMMENTED** [review]
looks good

**Comment by benlipkin** [comment]
could you change the same line in container interface as well? I take it this is since we now that the extra loop over the benchmark context groups which made the output crowded?

**Comment by mschrimpf** [comment]
done.

**Review by benlipkin — APPROVED** [review]
looks good. thanks for updating the Path type hint as well

**Pull request merged**
