### PR TITLE
relax python version to `>=3.7`

### PR DESCRIPTION
**Pull request by mschrimpf**
might depend on https://github.com/brain-score/core/pull/8

### CODE REVIEW

**Review by kvfairchild — APPROVED** [review]
(Approval conditional on https://github.com/brain-score/core/pull/8 passing the `3.7` and `3.9` builds)

**Comment by mschrimpf** [comment]
re-trigger after https://github.com/brain-score/core/pull/8 merge

**Comment by mschrimpf** [comment]
re-trigger

**Comment by mschrimpf** [comment]
Travis isn't triggering, trying to reopen again

**Pull request closed without merging**
