### PR TITLE
setup linting

### PR DESCRIPTION
**Pull request by mschrimpf**

### CODE REVIEW

**Comment by mschrimpf** [comment]
Running a linter works now, but current linting score is very poor, so the check fails

**Comment by kvfairchild** [comment]
Did we want to combine this with `black` and/or `autopep8` for automatic cleanup?

**Comment by mschrimpf** [comment]
I think it would be great if we could add `black`/`autopep8`, but would see that as a separate PR -- @benlipkin @kvfairchild do either of you have experience with running these automatically?

**Comment by kvfairchild** [comment]
Not sure about the latter, but there's an [official Actions integration](https://black.readthedocs.io/en/stable/integrations/github_actions.html) for `black`

**Review by kvfairchild — APPROVED** [review]

**Pull request merged**
