### PR TITLE
fix syntaxgym sub-benchmark prefixes in integration test; pull overall syntaxgym test into plugin

### PR DESCRIPTION
**Pull request by mschrimpf**
One of the syntaxgym (`npz_obj`) scores has changed as well as one of the `distilgpt2` `Pereira243` scores, I'm guessing as a result of model updates. @jimn2 if ok with you I just updated those numbers and we'll try to set up an integration test runner going forward.

All tests now pass again:
image

### CODE REVIEW

**Comment by jimn2** [comment]
I see you changed npz_obj from 0.916667 to 0.83333333.  I'm not sure exactly what was changed in the model but I have a very small red flag wondering why changing the model would only affect that one benchmark score.  I can think of how it's possible though and if that makes sense to you, then this is ok.

Also, what is an integration test runner?  Doesn't test_integration.py get run automatically already?  Thanks!

**Comment by mschrimpf** [comment]
I don't know either. My reasoning was basically that if there was no strong reason for the previous score (e.g. published precedence), then we can just set the new one as the standard.

By integration test runner, I just meant a test runner that can actually execute our integration tests. Travis unfortunately can't due to memory and time restrictions. In vision, we use jenkins on our own servers which I hope we can set up here as well.

**Review by jimn2 — APPROVED** [review]
will follow up with jon g to see if an additional note about the benchmark value change is appropriate.

**Comment by mschrimpf** [comment]
I'll merge for now since I haven't heard otherwise, but please let me know if something should be changed.

**Pull request merged**
