### PR TITLE
Fix failing SyntaxGym tests

### PR DESCRIPTION
**Pull request by kvfairchild**
Due to a bug likely introduced in the plugin management migration, Travis has not been appropriately flagging builds where a plugin is failing. This resulted in SyntaxGym merging to main while in a failing state (see [jobs in build #899](https://app.travis-ci.com/github/brain-score/language/jobs/590582378)). 

This PR implements some changes necessary for SyntaxGym to pass Travis checks:
* import path update
* two dependencies (`pandas`, `pyparsing`) added to a `requirements.txt`

### CODE REVIEW

**Comment by kvfairchild** [comment]
@jimn2: with these updates, all tests specified in `test.py` pass except for `test_syntaxgym2020_data`, which expects `SyntaxGym2020` to have 31 `sub_benchmarks` when it actually has 3. I'm not sure which value is desired here; can you add a fix for that?

**Comment by jimn2** [comment]
There are two ways to fix this; one trivially simple, the other taking a bit more time (and in my opinion giving no advantage over the trivial fix; I noticed that Jon only used 2 when he tested the aggregate in test.py).  

The first (trivial) fix is to switch the expected value of sub_benchmarks from 31 to 3.  SyntaxGym2020 executes the multi-suite capability of the benchmark which runs multiple suites and then takes the mean of the scores (and test_syntaxgym2020_data is testing part of that capability).  It's currently set up to run 3 suites and return the mean...so switching from 31 to 3 is correct for the current setup.   

The second way is to switch SyntaxGym2020 to run and return the mean of all 31 benchmarks.  While it wouldn't be a huge time investment to do this, it wouldn't be trivial.

I just pushed a fix that uses the first method (switching 31->3). 

Hopefully this works, let me know if it doesn't or if you want me to switch SyntaxGym2020 to running/averaging all 31 suites.

**Comment by jimn2** [comment]
(Sorry if I'm misinterpreting it, but) It looks like the SyntaxGym tests are passing but it's saying there's an Assertion Error with a few of the plugin tests.  Could you let me know how you'd like me to proceed?  Thanks!

**Review by jimn2 — APPROVED** [review]
I think the SG tests are passing now.

**Comment by jimn2** [comment]
(Not sure if I was supposed to approve given one check is still not passing but didn't want to be a blocker since the part you asked me to look at seems to be passing now.)

**Comment by kvfairchild** [comment]
@jimn2 what you've got is great, thanks! (And thanks for the approval as well - totally appropriate as the failures are not related to this PR / SyntaxGym)

**Comment by hans** [comment]
@jimn2  Why does `SyntaxGym2020` only run 3 suites? I missed this change in the main SyntaxGym PR I guess. `SyntaxGym2020` should certainly reference all the suites. Pushing a change to this effect now.

**Comment by jimn2** [comment]
@hans when figuring out how to split this into the 31 individual benchmarks, I cut the number of suites in SyntaxGym2020 because it was taking so long to run all 31.  And as SyntaxGym2020 is just providing the multi-suite-with-averaged-scores capability (and each of the 31 individual benchmarks are being tested in test_integration.py), it didn't seem to matter to me whether or not it's averaging all or a few to validate the averaging capability.

As an added note: while all 31 individual benchmarks are being tested in test_integration.py; at Martin's request SyntaxGym2020 is not being tested there (I had it being tested there having calculated the "true" average score for the first three suites manually).  It should probably be tested somewhere (maybe test.py?) but I'm not sure what the actual value of the average for all 31 scores should be.  The way it's set up right now, I don't think anything will be validating the averaged score that SyntaxGym2020 comes up with.

**Pull request merged**
